# Generated by Django 5.1.2 on 2025-01-10 22:22

import cashflow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.CharField(default=cashflow.models.get_persian_date, max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('cate_choices', models.CharField(choices=[('needs', 'نیازها'), ('wants', 'خواسته ها'), ('else', 'سایر'), ('parent', 'والدین'), ('part_time_job', 'کار نیمه\u200cوقت'), ('other', 'دیگر')], default='needs', max_length=20)),
                ('type', models.CharField(choices=[('expense', 'برآمد'), ('income', 'درآمد')], default='expense', max_length=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='cashflow.child')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20)),
                ('goal_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('جاری', 'جاری'), ('کامل', 'کامل')], default='جاری', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cashflow.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cashflow.parent'),
        ),
    ]
